version: "3.8"

services:
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/eva00
    env_file:
      - .env
    command: python app.py
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/mysanic.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always
